import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { adminPages, adminWidgets, allowedHosts, capabilities, editorPanels, PLUGIN_ID, PLUGIN_VERSION, settingsSchema } from '../src/plugin/manifest.ts';

/**
 * Writes emdash-plugin.jsonc, the manifest EmDash's plugin CLI and registry
 * use for the sandboxed plugin, from src/plugin/manifest.ts:
 *
 *   tsx scripts/write-manifest.ts [--check]
 */

const file = fileURLToPath(new URL('../emdash-plugin.jsonc', import.meta.url));
const manifest = {
	$schema: 'https://emdashcms.com/schemas/emdash-plugin.schema.json',
	slug: PLUGIN_ID,
	version: PLUGIN_VERSION,
	publisher: 'did:plc:replace-with-your-publisher-did',
	license: 'Apache-2.0',
	author: { name: 'Graft contributors', url: 'https://github.com/swissspidy/graft' },
	security: { url: 'https://github.com/swissspidy/graft/security/advisories/new' },
	name: 'Graft',
	description: 'Durable, spec-driven customizations: verified builds served as Block Kit, upgraded when EmDash changes.',
	capabilities: [...capabilities],
	allowedHosts,
	storage: {},
	admin: { pages: adminPages, widgets: adminWidgets, editorPanels, settingsSchema },
};
const json = `// Generated by scripts/write-manifest.ts from src/plugin/manifest.ts. Do not edit.\n${JSON.stringify(manifest, null, '\t').replace('"publisher"', '// Replace with your atproto DID before publishing to the registry.\n\t"publisher"')}\n`;
if (process.argv.includes('--check')) {
	if ((await readFile(file, 'utf8').catch(() => '')) !== json) {
		console.error('emdash-plugin.jsonc is out of date. Run: pnpm manifest:emdash');
		process.exit(1);
	}
	console.log('emdash-plugin.jsonc is up to date.');
} else {
	await writeFile(file, json);
	console.log('Wrote emdash-plugin.jsonc');
}
